apify/actor-templates

build/examples/map_and_reduce.md, examples/accept_user_input/accept_user_input.md, examples/basic_crawler/basic_crawler.md, examples/call_actor/call_actor.md, examples/cheerio_crawler/cheerio_crawler.md, examples/crawl_all_links/crawl_all_links.md, examples/crawl_multiple_urls/crawl_multiple_urls.md, examples/crawl_relative_links/crawl_relative_links.md, examples/crawl_single_url/crawl_single_url.md, examples/crawl_sitemap/crawl_sitemap.md, examples/crawl_some_links/crawl_some_links.md, examples/forms/forms.md, examples/puppeteer_sitemap/puppeteer_sitemap.md, examples/puppeteer_with_proxy/puppeteer_with_proxy.md, examples/screenshots/screenshots.md, examples/synchronous_run/synchronous_run.md
The links to 'map' and 'reduce' don't work right now, but I'm guessing they will once it's built, right?
=> Proofread map_and_reduce

templates/cheerio_crawler/INPUT_SCHEMA.json, templates/cheerio_crawler/README.md, templates/cheerio_crawler/apify_storage/key_value_stores/default/INPUT.json, templates/cheerio_crawler/main.js, templates/cheerio_crawler/package.json, templates/cheerio_crawler/src/routes.js, templates/puppeteer_crawler/INPUT_SCHEMA.json, templates/puppeteer_crawler/README.md, templates/puppeteer_crawler/apify_storage/key_value_stores/default/INPUT.json, templates/puppeteer_crawler/main.js, templates/puppeteer_crawler/package.json, templates/puppeteer_crawler/src/routes.js
Better late than never, the promised template that can be used to bootstrap projects by any developer working regularly with the SDK.
I suggest using the [direct file link ](https://github.com/apifytech/actor-templates/blob/e36eb7ead6ed200fe6d30056c06f6a620cdba244/templates/cheerio_crawler/main.js)for review. The changes are irrelevant. I replaced the existing cheerio template.
Do you think I should add more details? I didn't want to stuff it with examples that the devs would have to delete every time.
Once we agree, I'll do the `PuppeteerCrawler` one in similar fashion.
=> Update examples to production grade

templates/example_hello_world/README.md, templates/example_puppeteer_single_page/README.md, templates/project_cheerio_crawler/README.md, templates/project_empty/README.md, templates/project_playwright_crawler/README.md, templates/project_puppeteer_crawler/README.md
Following the conversation here
https://apifier.slack.com/archives/CDXELTEPN/p1615974311012900
The table of contents markers are needed for optimal displaying on the actor detail page on web.
I hope I've done it right :D
=> Update readme with ToC info

templates/example_hello_world/Dockerfile, templates/example_puppeteer_single_page/Dockerfile, templates/project_cheerio_crawler/Dockerfile, templates/project_empty/Dockerfile, templates/project_playwright_crawler/Dockerfile, templates/project_puppeteer_crawler/Dockerfile
It will work how it used to work with npm 6
https://docs.npmjs.com/cli/v7/commands/npm-ls#all
=> npm 7 requires --all for list

templates/example_hello_world/Dockerfile, templates/example_puppeteer_single_page/Dockerfile, templates/example_typescript/Dockerfile, templates/project_cheerio_crawler/Dockerfile, templates/project_empty/Dockerfile, templates/project_playwright_crawler/Dockerfile, templates/project_puppeteer_crawler/Dockerfile
Closes https://github.com/apify/apify-actor-docker/issues/60
=> chore: ignore dev deps when calling `npm list`

templates/getting_started_typescript/src/main.ts
Fixed getting started typescript template, which cannot be build on platform because typecheck failed.
=> fix: getting started typescript template

templates/getting_started_node/.actor/actor.json, templates/getting_started_python/.actor/actor.json, templates/getting_started_typescript/.actor/actor.json
Resolves this issues: https://github.com/apify/apify-core/issues/8237
Updated the templates to follow the new output schema definition with docs here: https://docs.apify.com/actors/development/output-schema#viewtransformation-object-definition
Tested it and both worker and UI already have it implemented.
=> Updates templates based on new output documentation

templates/getting_started_typescript/.actor/Dockerfile, templates/project_cheerio_crawler_ts/.actor/Dockerfile, templates/project_playwright_crawler_ts/.actor/Dockerfile, templates/project_puppeteer_crawler_ts/.actor/Dockerfile
This should __actually__ speed up cached builds on code-only changes
=> Install packages before copying dist folder

templates/getting_started_node/.actor/actor.json, templates/getting_started_python/.actor/actor.json, templates/getting_started_typescript/.actor/actor.json
=> fix: fixing dockefile typos

templates/manifest.json
Adding showcase files to show them in template details (as we don't want to show all of them). Design and arguments described in [following issue](https://github.com/apify/apify-web/issues/2545).
Feel free to suggest different/more files for showcase.
=> feat(app): add showcase files to manifest.json

src/index.js, templates/manifest.json
Added the suffix files urls into the manifest so that we do not have to publish new version of this repo. Instead where needed we will fetch directly from the url in manifest.
=> feat: manifest suffix urls

templates/manifest.json
=> feat: add use cases to manifest

templates/js-cypress/README.md, templates/js-cypress/cypress.config.js, templates/js-cypress/package.json, templates/js-cypress/src/main.js
- updated README
- moved main.js to src/main.js
- added code comments
closes apify/apify-web#2673
=> feat(js-cypress): readme update

templates/js-bootstrap-cheerio-crawler/src/main.js, templates/js-crawlee-cheerio/src/main.js, templates/js-crawlee-playwright-chrome/src/main.js, templates/js-crawlee-puppeteer-chrome/src/main.js, templates/js-cypress/src/main.js, templates/js-empty/src/main.js, templates/js-langchain/src/main.js, templates/js-start/src/main.js, templates/ts-bootstrap-cheerio-crawler/src/main.ts, templates/ts-crawlee-cheerio/src/main.ts, templates/ts-crawlee-playwright-chrome/src/main.ts, templates/ts-crawlee-puppeteer-chrome/src/main.ts, templates/ts-empty/src/main.ts, templates/ts-start/src/main.ts
Related: https://apifier.slack.com/archives/C0L33UM7Z/p1694422682340699
=> docs: add a comment to all the `main` files about ESM and import extensions

templates/js-crawlee-playwright-chrome/package.json, templates/ts-crawlee-playwright-chrome/package.json, templates/ts-playwright-test-runner/package.json
Related: https://github.com/apify/crawlee/pull/2104
=> chore: add postinstall command for playwright templates

README.md
Fix deadlinks or add missing links (empty projects)
=> Fix deadlinks in the repository README

templates/python-scrapy/src/__main__.py, wrappers/python-scrapy/{projectFolder}/__main__.template.py
=> Python Scrapy Actor: Improve logging configuration

wrappers/python-scrapy/{projectFolder}/__main__.template.py, wrappers/python-scrapy/{projectFolder}/main.template.py
=> Improve docs of the Apify Scrapy template (in wrappers)

templates/python-scrapy/src/__main__.py, templates/python-scrapy/src/items.py, templates/python-scrapy/src/main.py, templates/python-scrapy/src/pipelines.py, templates/python-scrapy/src/settings.py, templates/python-scrapy/src/spiders/__init__.py, templates/python-scrapy/src/spiders/title.py, wrappers/python-scrapy/{projectFolder}/__main__.template.py, wrappers/python-scrapy/{projectFolder}/main.template.py
Closes #235
I decided to split solution to the #235 into at least 2 PRs. One for the Scrapy, since it is the biggest template by far, ale the second one will be for other templates.
=> Scrapy template: Minor code update and docs improvement

templates/python-beautifulsoup/requirements.txt, templates/python-beautifulsoup/src/__main__.py, templates/python-beautifulsoup/src/main.py, templates/python-empty/requirements.txt, templates/python-empty/src/__main__.py, templates/python-empty/src/main.py, templates/python-playwright/requirements.txt, templates/python-playwright/src/__main__.py, templates/python-playwright/src/main.py, templates/python-scrapy/requirements.txt, templates/python-selenium/requirements.txt, templates/python-selenium/src/__main__.py, templates/python-selenium/src/main.py, templates/python-start/requirements.txt, templates/python-start/src/__main__.py, templates/python-start/src/main.py
=> Python templates: code finetuning, improve docs and comments

templates/python-beautifulsoup/.actor/Dockerfile, templates/python-empty/.actor/Dockerfile, templates/python-playwright/.actor/Dockerfile, templates/python-scrapy/.actor/Dockerfile, templates/python-selenium/.actor/Dockerfile, templates/python-start/.actor/Dockerfile
=> Python templates: Add code check step to the Dockerfiles

templates/python-scrapy/.actor/input_schema.json, templates/python-scrapy/README.md, templates/python-scrapy/src/main.py, templates/python-scrapy/src/settings.py
=> Python Scrapy: Rm `max_depth` from default Actor input

templates/python-scrapy/.dockerignore, templates/python-scrapy/.gitignore, wrappers/python-scrapy/.actor/Dockerfile.template, wrappers/python-scrapy/.actor/input_schema.template.json, wrappers/python-scrapy/.dockerignore, wrappers/python-scrapy/.gitignore, wrappers/python-scrapy/{projectFolder}/main.template.py
=> Scrapy Actor: Align changes between templates wrappers

templates/python-scrapy/src/middlewares.py, templates/python-scrapy/src/settings.py
=> Scrapy Actor: Add middlewares module

templates/manifest.json
Closes apify/apify-core#13328
Move scrapy to first position to promote it around Apify platform/web.
=> feat: reorder scrapy

wrappers/python-scrapy/{projectFolder}/__main__.template.py
In https://github.com/apify/actor-templates/pull/246 I forgot to update the `wrappers/` :see_no_evil: .
=> Scrapy Actor wrapper: Set logging level of HTTPX to WARNING

templates/python-scrapy/src/__main__.py, wrappers/python-scrapy/{projectFolder}/__main__.template.py
=> Scrapy Actor: Fix duplicate log messages (p2)

templates/python-beautifulsoup/requirements.txt, templates/python-empty/requirements.txt, templates/python-playwright/requirements.txt, templates/python-scrapy/.actor/actor.json, templates/python-scrapy/.actor/input_schema.json, templates/python-scrapy/requirements.txt, templates/python-scrapy/src/main.py, templates/python-scrapy/src/middlewares.py, templates/python-scrapy/src/settings.py, templates/python-selenium/requirements.txt, templates/python-start/requirements.txt, wrappers/python-scrapy/.actor/actor.template.json, wrappers/python-scrapy/.actor/input_schema.template.json, wrappers/python-scrapy/requirements_apify.txt, wrappers/python-scrapy/{projectFolder}/main.template.py
- Closes: https://github.com/apify/actor-templates/issues/255
- After the SDK update (https://github.com/apify/apify-sdk-python/pull/158) is merged, release a new version, and use it here.
- Once we finish the review process, update the [scrapy wrapper](https://github.com/apify/actor-templates/tree/master/wrappers/python-scrapy) and [actor-scrapy-books-example](https://github.com/apify/actor-scrapy-books-example/).
=> Add Scrapy `ApifyHttpProxyMiddleware` for managing proxies

templates/python-beautifulsoup/requirements.txt, templates/python-empty/requirements.txt, templates/python-playwright/requirements.txt, templates/python-scrapy/requirements.txt, templates/python-scrapy/src/main.py, templates/python-selenium/requirements.txt, templates/python-start/requirements.txt, wrappers/python-scrapy/requirements_apify.txt, wrappers/python-scrapy/{projectFolder}/main.template.py
Closes: https://github.com/apify/actor-templates/issues/202
=> Update documentation of Scrapy Actor template

templates/python-beautifulsoup/requirements.txt, templates/python-empty/requirements.txt, templates/python-playwright/requirements.txt, templates/python-scrapy/requirements.txt, templates/python-scrapy/src/main.py, templates/python-selenium/requirements.txt, templates/python-start/requirements.txt, wrappers/python-scrapy/requirements_apify.txt
Related to the https://github.com/apify/apify-sdk-python/pull/178. Merge it and release a new version of SDK before merging this.
=> Scrapy Actor: Move `_get_scrapy_settings` to SDK

templates/js-langchain/package.json
=> chore: update langchain to fix tests

CONTRIBUTING.md, templates/python-beautifulsoup/requirements.txt, templates/python-empty/requirements.txt, templates/python-playwright/requirements.txt, templates/python-scrapy/requirements.txt, templates/python-selenium/requirements.txt, templates/python-start/requirements.txt, test/templates.test.js, wrappers/python-scrapy/requirements_apify.txt
Tmp fix, until https://github.com/apify/actor-templates/issues/270 is resolved.
=> Fix python templates: SDK == 1.5.3

templates/python-beautifulsoup/requirements.txt, templates/python-empty/requirements.txt, templates/python-playwright/requirements.txt, templates/python-scrapy/requirements.txt, templates/python-scrapy/src/__main__.py, templates/python-selenium/requirements.txt, templates/python-start/requirements.txt, wrappers/python-scrapy/requirements_apify.txt
As part of https://github.com/apify/apify-sdk-python/issues/185
=> Update to Apify 1.6.0 and Scrapy 2.11.1

templates/js-standby/.actor/Dockerfile, templates/js-standby/.actor/actor.json, templates/js-standby/.dockerignore, templates/js-standby/.editorconfig, templates/js-standby/.eslintrc, templates/js-standby/.gitignore, templates/js-standby/README.md, templates/js-standby/package.json, templates/js-standby/src/main.js, templates/manifest.json, templates/python-standby/.actor/Dockerfile, templates/python-standby/.actor/actor.json, templates/python-standby/README.md, templates/python-standby/requirements.txt, templates/python-standby/src/__main__.py, templates/python-standby/src/main.py, templates/ts-standby/.actor/Dockerfile, templates/ts-standby/.actor/actor.json, templates/ts-standby/.dockerignore, templates/ts-standby/.gitignore, templates/ts-standby/README.md, templates/ts-standby/package.json, templates/ts-standby/src/main.ts, templates/ts-standby/tsconfig.json
This PR adds templates for Actor Standby.
=> feat: add Actor Standby templates

templates/python-beautifulsoup/requirements.txt, templates/python-crawlee-beautifulsoup/requirements.txt, templates/python-crawlee-playwright/requirements.txt, templates/python-empty/requirements.txt, templates/python-playwright/requirements.txt, templates/python-scrapy/requirements.txt, templates/python-selenium/requirements.txt, templates/python-standby/requirements.txt, templates/python-start/requirements.txt, wrappers/python-scrapy/requirements_apify.txt
=> chore: Enforce only major versions for Python projects

templates/manifest.json, templates/python-crawlee-beautifulsoup/requirements.txt, templates/python-crawlee-beautifulsoup/src/main.py, templates/python-crawlee-playwright/requirements.txt, templates/python-crawlee-playwright/src/main.py, templates/python-scrapy/requirements.txt, templates/python-scrapy/src/__main__.py, templates/python-scrapy/src/items.py, templates/python-scrapy/src/middlewares.py, templates/python-scrapy/src/pipelines.py, templates/python-scrapy/src/spiders/__init__.py, templates/python-scrapy/src/spiders/title.py
- Pin Crawlee & Scrapy versions
- Fixing Scrapy template
=> fix: Fix Python templates to work with Crawlee v0.5

templates/python-beautifulsoup/src/main.py, templates/python-crawlee-beautifulsoup/src/main.py, templates/python-crawlee-playwright/src/main.py, templates/python-playwright/src/main.py, templates/python-selenium/src/main.py
A few minor updates to the Python templates that came to mind while working on [apify-sdk-python#378](https://github.com/apify/apify-sdk-python/pull/378). I wanted to propagate these updates here as well, as the templates are closely aligned with the code used in the guides.
=> chore: Update of Python templates

templates/ts-bee-agent/.actor/input_schema.json, templates/ts-bee-agent/src/main.ts, templates/ts-bee-agent/src/tools/instagram.ts
https://github.com/apify/actor-templates/issues/323
=> fix: ts-bee-agent template

templates/python-crewai/.actor/dataset_schema.json, templates/python-crewai/.actor/input_schema.json, templates/python-crewai/.actor/pay_per_event.json, templates/python-crewai/README.md, templates/python-crewai/src/main.py, templates/python-crewai/src/models.py, templates/python-crewai/src/ppe_utils.py, templates/python-crewai/src/tools.py
Clean code, token based ppe -> task based, align with the proposed build an AI agent article
=> fix: update crewai template

templates/python-crawlee-playwright/src/main.py
based on https://apify.slack.com/archives/C0L33UM7Z/p1741278934497689
=> fix: python-crawlee-playwright add no sandbox

templates/js-crawlee-playwright-camoufox/.actor/Dockerfile, templates/js-crawlee-playwright-camoufox/package.json, templates/ts-crawlee-playwright-camoufox/.actor/Dockerfile, templates/ts-crawlee-playwright-camoufox/package.json
Related: https://github.com/apify/crawlee/pull/2879
=> fix: pin playwright to 1.50.1 in camoufox templates

package-lock.json, package.json, templates/js-crawlee-playwright-camoufox/.actor/Dockerfile, templates/js-crawlee-playwright-camoufox/package.json, templates/ts-crawlee-playwright-camoufox/.actor/Dockerfile, templates/ts-crawlee-playwright-camoufox/package.json
Related: https://github.com/daijro/camoufox/discussions/230
=> fix: unpin playwright in camoufox templates

.github/workflows/lint_and_test.yaml, Makefile, pyproject.toml, templates/python-beautifulsoup/src/main.py, templates/python-crawlee-beautifulsoup/src/main.py, templates/python-crawlee-playwright/src/main.py, templates/python-crewai/src/main.py, templates/python-crewai/src/models.py, templates/python-crewai/src/tools.py, templates/python-empty/src/main.py, templates/python-langgraph/src/main.py, templates/python-langgraph/src/models.py, templates/python-langgraph/src/tools.py, templates/python-langgraph/src/utils.py, templates/python-llamaindex-agent/src/agent.py, templates/python-llamaindex-agent/src/main.py, templates/python-playwright/src/main.py, templates/python-scrapy/src/items.py, templates/python-scrapy/src/main.py, templates/python-scrapy/src/middlewares.py, templates/python-scrapy/src/pipelines.py, templates/python-scrapy/src/spiders/title.py, templates/python-selenium/src/main.py, templates/python-standby/src/main.py, templates/python-start/src/main.py, uv.lock, wrappers/python-scrapy/{projectFolder}/__main__.template.py, wrappers/python-scrapy/{projectFolder}/main.template.py
=> ci: Add Python type checks

templates/manifest.json
Report: https://apify.slack.com/archives/C0L33UM7Z/p1742463940103169
=> fix: make camoufox template names unique

templates/manifest.json, templates/python-pydanticai/.actor/Dockerfile, templates/python-pydanticai/.actor/actor.json, templates/python-pydanticai/.actor/input_schema.json, templates/python-pydanticai/.actor/pay_per_event.json, templates/python-pydanticai/.dockerignore, templates/python-pydanticai/.gitignore, templates/python-pydanticai/README.md, templates/python-pydanticai/requirements.txt, templates/python-pydanticai/src/__main__.py, templates/python-pydanticai/src/agents.py, templates/python-pydanticai/src/main.py
=> feat: Add PydanticAI template

templates/manifest.json
Part of this -> https://github.com/apify/apify-web/issues/4581
=> feat: add AI use case to manifest

.github/workflows/lint_and_test.yaml
Discovered here: https://github.com/apify/actor-templates/pull/364
=> chore: Run tests on fork based PRs

.github/workflows/lint_and_test.yaml
Reverts apify/actor-templates#370
It does not seem very safe. It runs with secrets, but I did not manage to set up suitable control over when such forked PRs will be allowed to run.
=> Revert "chore: Run tests on fork based PRs"

Makefile, pyproject.toml, templates/manifest.json, templates/python-crewai/requirements.txt, templates/python-langgraph/requirements.txt, templates/python-llamaindex-agent/requirements.txt, templates/python-smolagents/.actor/Dockerfile, templates/python-smolagents/.actor/actor.json, templates/python-smolagents/.actor/input_schema.json, templates/python-smolagents/.dockerignore, templates/python-smolagents/.gitignore, templates/python-smolagents/README.md, templates/python-smolagents/requirements.txt, templates/python-smolagents/src/__main__.py, templates/python-smolagents/src/main.py, uv.lock
- Add Python AI Agent Actor template using [Smolagents](https://huggingface.co/docs/smolagents/index).
- The template Actor is an AI news aggregator that fetches and summarizes the latest news based on user-defined interests. 
- It utilizes DuckDuckGo search and OpenAI models in Python Smolagents.
- I added an upper version boundary for the next major release of the AI packages.
- Closes: https://github.com/apify/actor-templates/issues/369
=> feat: add Smolagents Python Actor template

templates/js-crawlee-cheerio/src/main.js, templates/js-crawlee-playwright-camoufox/src/main.js, templates/js-crawlee-playwright-chrome/src/main.js, templates/ts-crawlee-cheerio/.actor/input_schema.json, templates/ts-crawlee-cheerio/src/main.ts, templates/ts-crawlee-playwright-camoufox/.actor/input_schema.json, templates/ts-crawlee-playwright-camoufox/src/main.ts, templates/ts-crawlee-playwright-chrome/.actor/input_schema.json, templates/ts-crawlee-playwright-chrome/src/main.ts, templates/ts-crawlee-puppeteer-chrome/src/main.ts
=> fix: use apify.com consistently as the startUrls/globs

pyproject.toml, templates/python-pydanticai/requirements.txt, templates/python-pydanticai/src/agents.py, templates/python-pydanticai/src/main.py, uv.lock
Update example to not crash with latest pydanticai
Lock requirements with pydanticai ~= 0.1.0
=> Update pydanticai example to lastest release of the package

Makefile, templates/manifest.json, templates/python-crawlee-playwright-camoufox/.actor/actor.json, templates/python-crawlee-playwright-camoufox/.actor/input_schema.json, templates/python-crawlee-playwright-camoufox/.dockerignore, templates/python-crawlee-playwright-camoufox/.gitignore, templates/python-crawlee-playwright-camoufox/Dockerfile, templates/python-crawlee-playwright-camoufox/README.md, templates/python-crawlee-playwright-camoufox/requirements.txt, templates/python-crawlee-playwright-camoufox/src/__main__.py, templates/python-crawlee-playwright-camoufox/src/main.py
- Add crawlee + playwright + camoufox template
- Closes: #482
=> feat: Add python crawlee playwright with camoufox template

templates/ts-mcp-server/src/mcp.ts
Initialization for remote servers was not working since we were sending the initialization request twice, once from mcp-remote and then the forwarded one from the actual client. Fixed this by not forwarding the initaizazed notification and returning response for initialize requests directly with the server capabilities.
=> fix(ts-mcp-server): do not forward initialization requests to remote servers

templates/python-mcp-server/README.md, templates/python-mcp-server/src/const.py, templates/python-mcp-server/src/main.py, templates/python-mcp-server/src/mcp_gateway.py, templates/python-mcp-server/src/server.py
Add HTML page at standby urls `/` and `/mcp` to inform users
FYI @ivanvia7  and @MichalKalita
=> feat: Python MCP add HTML at / and /mcp
