apify/actor-templates

- templates/example_python/main.py
This is so that the client and template works properly in more environments than just the production Apify app. Tests are failing for reasons unrelated to this change.
> Pass API url to client from environment variable in Python template

- templates/project_cheerio_crawler/INPUT_SCHEMA.json
- templates/project_playwright_crawler/INPUT_SCHEMA.json
- templates/project_puppeteer_crawler/INPUT_SCHEMA.json
This PR adds prefill values to INPUT_SCHEMAS of cheerio, pupetteer and playwright crawlers, so that the actor created from this template could be started with no changes. The run itself can fail later.
Letting know @metalwarrior665
> Add required fields as prefills to input schemas

- templates/getting_started_node/.actor/actor.json
- templates/getting_started_node/Dockerfile
- templates/getting_started_node/INPUT_SCHEMA.json
- templates/getting_started_node/README.md
- templates/getting_started_node/package.json
- templates/getting_started_node/src/main.js
- templates/getting_started_python/.actor/actor.json
- templates/getting_started_python/Dockerfile
- templates/getting_started_python/INPUT_SCHEMA.json
- templates/getting_started_python/README.md
- templates/getting_started_python/main.py
- templates/getting_started_python/requirements.txt
- templates/getting_started_typescript/.actor/actor.json
- templates/getting_started_typescript/Dockerfile
- templates/getting_started_typescript/INPUT_SCHEMA.json
- templates/getting_started_typescript/README.md
- templates/getting_started_typescript/package.json
- templates/getting_started_typescript/src/main.ts
- templates/getting_started_typescript/tsconfig.json
- templates/manifest.json
- test/templates.test.js
Adding templates that should be used in developer onboarding flow of the Console. It should work approximately like this:
1. Users are prompted to create an actor.
2. They are presented with 3 language choices - Node, TS, Python
3. Depending on choice, the proper getting started template is selected
4. They are prompted to complete the missing piece of code
5. Build
6. Prompted to go to Input - which will have input schema
7. Fill in input
8. Run
9. Output schema should kick in and show nice table
10. Prompt to either deploy code from GitHub (go to GitHub guide), from local (CLI guide) or continue browsing Console.
@B4nan pls check the TS. I skipped build, because the code would not build, as there is a piece missing.
@fnesveda pls check the Python. I used your original example and quite …
> Add getting started templates

- templates/crawlee_cheerio_typescript/Dockerfile
- templates/crawlee_playwright_typescript/Dockerfile
- templates/crawlee_puppeteer_typescript/Dockerfile
- templates/example_hello_world/Dockerfile
- templates/example_puppeteer_single_page/Dockerfile
- templates/example_typescript/Dockerfile
- templates/getting_started_typescript/Dockerfile
- templates/project_cheerio_crawler/Dockerfile
- templates/project_empty/Dockerfile
- templates/project_playwright_crawler/Dockerfile
- templates/project_puppeteer_crawler/Dockerfile
I suggest using `npm ci` in templates for faster and deterministic builds. All flags used (`--no-optional`, `--include=`, `--only`) have the same behavior for `npm ci` based on my testing. Sadly, they are not properly documented in the npm docs...
> use npm ci instead of npm install

- templates/crawlee_cheerio_typescript/Dockerfile
- templates/crawlee_playwright_typescript/Dockerfile
- templates/crawlee_puppeteer_typescript/Dockerfile
- templates/example_hello_world/Dockerfile
- templates/example_puppeteer_single_page/Dockerfile
- templates/example_typescript/Dockerfile
- templates/getting_started_typescript/Dockerfile
- templates/project_cheerio_crawler/Dockerfile
- templates/project_empty/Dockerfile
- templates/project_playwright_crawler/Dockerfile
- templates/project_puppeteer_crawler/Dockerfile
Reverts apify/actor-templates#98
As it is not possible to run `npm ci` without existing lock file.
> Revert "use npm ci instead of npm install"

- templates/getting_started_typescript/.actor/actor.json
I was testing my changes on staging and noticed this:
Turns out that the default output schema for `Getting started: TypeScript` is wrong - the display object contains another display object...
> Fix output schema in getting started TS

- README.md
Update the README to reflect the current actor template structure, as specified in this Notion document -> https://www.notion.so/apify/Make-changes-to-the-template-s-description-in-GitHub-f7841752371c4da6b3d4d4c5bb90bc49
We might have to revisit this README after the Python SDK launch and the addition of new Python templates.
> update templates README

- templates/manifest.json
This PR is mostly about unifying the template labels and improving descriptions, but I also thought it might be useful to add another field to the manifest: `replacements` (name up for discussion).
The purpose of replacements is to have CLI redirects between templates. Now if we remove a template, CLI integrations that use `-t` will break. With the replacements field, we could redirect them to new/updated/similar templates. I'm not sure if it's super important, but it feels a bit safer than simply deleting templates.
I removed the language from most labels, because it felt super repetitive and especially in the CLI it does not make sense, because you first select the language and then you would see ... Python, ... Python ... Python everywhere. Let me know what you think.
> feat: add template replacements, update descriptions and labels

- templates/manifest.json
People running actors made from these templates had their runs super slow because running a browser with 1GB of memory is not a great experience. This should make it better for them.
> Increase memory for Python templates that use browsers

- templates/ts-playwright-test-runner/package.json
This template is using the dev mode currently, which uses ts-node and hence requires tsconfig to be present.
Also moved the eslint config dependency there to be safer, we should clean this up later, together with changes in the dockerfile (unless there is an actual need to run things with ts-node).
> fix: move dev dependencies to regular dependencies

- .github/workflows/lint_and_test.yaml
Apparently, if you pass `chromedriver-version` to `setup-chromedriver`, it will install the given Chromedriver version, but it will also install latest Chrome which might not be compatible to the given Chromedriver version. 
There is now a better way to install the same Chrome and Chromedriver, using [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/) and `npx @puppeteer/browsers install ...`.
> fix: Specify the same Chrome and Chromedriver version in tests

- templates/python-scrapy/requirements.txt
Closes #178 
It's Scrapy's bug - https://github.com/scrapy/scrapy/issues/6024 , this PR provides a hotfix.
Remove it once the Scrapy gets updated / Twisted fixes it on their side
> Add Twisted version constraint

- templates/console_readme_suffix.md
The Apify CLI was accepted into `homebrew-core`, so the installation instructions got a bit simpler.
> chore: Update Apify CLI installation instructions via Homebrew

- .github/workflows/lint_and_test.yaml
- templates/js-crawlee-cheerio/.actor/Dockerfile
- templates/js-crawlee-playwright-chrome/.actor/Dockerfile
- templates/js-crawlee-playwright-chrome/package.json
- templates/js-crawlee-puppeteer-chrome/.actor/Dockerfile
- templates/ts-bootstrap-cheerio-crawler/package.json
- templates/ts-crawlee-cheerio/.actor/Dockerfile
- templates/ts-crawlee-cheerio/package.json
- templates/ts-crawlee-playwright-chrome/.actor/Dockerfile
- templates/ts-crawlee-playwright-chrome/package.json
- templates/ts-crawlee-puppeteer-chrome/.actor/Dockerfile
- templates/ts-crawlee-puppeteer-chrome/package.json
- templates/ts-empty/package.json
- templates/ts-playwright-test-runner/.actor/Dockerfile
- templates/ts-playwright-test-runner/package.json
- templates/ts-start/package.json
- change `ts-node-esm` to node loader instead to get around https://github.com/TypeStrong/ts-node/issues/1997
- adds node 20 to the CI checks
- use node 18 in all the docker images
- pin playwright dependency (both in package.json and dockerfile) to 1.37.1 as latest version is broken (cannot find the browser)
Closes #167
> fix ts-node on node 20 + update all images to use node 18

- templates/python-scrapy/requirements.txt
- templates/python-scrapy/src/__main__.py
- Add an option to configure a logging level
- for all the loggers out there - `apify`, `apify_client`, `scrapy`, `twisted`, `filelock`, `hpack`
- and on one place - at the beginning on the `__main__.py` file as a constant `LOGGING_LEVEL`
- Closes #185
- Since these Scrapy-Actor apps contain 6 different loggers I think it could be valuable to have a logger name at the beginning.
- Check the https://github.com/apify/apify-sdk-python/pull/116.
> Fix set logging level in Python Scrapy template

- templates/python-beautifulsoup/src/main.py
- templates/python-empty/src/main.py
- templates/python-playwright/src/main.py
- templates/python-scrapy/src/apify/main.py
- templates/python-scrapy/src/apify/middlewares.py
- templates/python-scrapy/src/apify/pipelines.py
- templates/python-scrapy/src/apify/scheduler.py
- templates/python-selenium/src/main.py
- templates/python-start/src/main.py
U used auto-formatters (`autopep8`, `isort`) that we use in our other Python libraries (`SDK`, `Client`) to format the Python Actor templates.
I also used linter (`flake8` with plugins we use in our other libs) to fix some violations, like "trailing comma" or "bare except".
> Format Python Actor templates

- templates/python-beautifulsoup/.actor/Dockerfile
- templates/python-beautifulsoup/README.md
- templates/python-beautifulsoup/requirements.txt
- templates/python-beautifulsoup/src/main.py
- templates/python-empty/.actor/Dockerfile
- templates/python-empty/README.md
- templates/python-empty/requirements.txt
- templates/python-empty/src/main.py
- templates/python-playwright/.actor/Dockerfile
- templates/python-playwright/README.md
- templates/python-scrapy/.actor/Dockerfile
- templates/python-scrapy/README.md
- templates/python-selenium/.actor/Dockerfile
- templates/python-selenium/README.md
- templates/python-start/.actor/Dockerfile
- templates/python-start/README.md
- templates/python-start/requirements.txt
- templates/python-start/src/main.py
- https://github.com/apify/actor-templates/issues/182
The motivation for usage of HTTPX is explained here: https://github.com/apify/actor-templates/issues/182#issuecomment-1748615100.
- All the templates that were using Requests (`python-beautifulsoup`, `python-start`) now use HTTPX.
- I also updated relevant texts in the readmes and in the code comments. 
- On top of that...
- I removed `beautifulsoup` from the `requirements.txt` of `python-empty` template (it was not used there).
- `actor` -> `Actor`
- Fix a few broken/wrong links (e.g. to JS instead of Python docs)
- Some unification of `## Included features` section in the README across all the Python Actors
> Use HTTPX instead of Requests in Python templates

- templates/python-scrapy/src/main.py
- wrappers/python-scrapy/{projectFolder}/main.template.py
While testing the Scrapy wrapper, I encountered a bug where the `ActorDatasetPushPipeline` with a priority number of 1 is being executed first. This makes all other item pipelines essentially useless. It should ideally be executed as the last one to perform all the necessary cleaning processes before storing the data.
From Scrapy docs (https://docs.scrapy.org/en/latest/topics/item-pipeline.html#activating-an-item-pipeline-component):
> The integer values you assign to classes in this setting determine the order in which they run: items go through from lower valued to higher valued classes. It’s customary to define these numbers in the 0-1000 range.
> Scrapy Actor: Update ActorDatasetPushPipeline from 1 to 1000

- templates/python-scrapy/src/__main__.py
Set the `HTTPX` logger explicitly to the `WARNING` level, because it is too verbose and spams the logs with useless messages, especially when running on the platform.
> Scrapy Actor: Set logging level of HTTPX to WARNING

- templates/ts-bootstrap-cheerio-crawler/package.json
- templates/ts-crawlee-cheerio/package.json
- templates/ts-crawlee-playwright-chrome/package.json
- templates/ts-crawlee-puppeteer-chrome/package.json
- templates/ts-empty/package.json
- templates/ts-playwright-test-runner/package.json
- templates/ts-start/package.json
- test/templates.test.js
Also unlocks TypeScript 5.3
---
Unrelated, but the code in `templates.test.js` looks wrong:
I'm not gonna touch it in this PR but this is something to keep in mind.
> chore: move to tsx for templates from ts-node

- templates/python-scrapy/src/__main__.py
- wrappers/python-scrapy/{projectFolder}/__main__.template.py
Scrapy Actor: Fix duplicate log messages, which were caused by our custom logging settings.
Closes: https://github.com/apify/actor-templates/issues/256
> Scrapy Actor: Fix duplicate log messages

- templates/js-crawlee-playwright-chrome/src/main.js
- templates/ts-crawlee-playwright-chrome/.actor/input_schema.json
- templates/ts-crawlee-playwright-chrome/src/main.ts
- Added missing `Actor.init()` at the top of the template code for `js-crawlee-playwright-chrome` template
- Switched `ts-crawlee-playwright-chrome` to a template with dynamic input URLs (we probably forgot to switch it while doing updates for the templates)
Reported in Slack #bugs channel https://apifier.slack.com/archives/C0L33UM7Z/p1705144932648779
> Fixed init for `js-crawlee-playwright-chrome` and dynamic input fro `ts-crawlee-playwright-chrome` template

- .eslintignore
- package.json
- src/index.d.cts
- src/index.d.mts
This module is used externally to fetch the manifests, and TS types are always nice to have
Result: (for this its fineee if its masquerading as ESM, as we use esm-compatible syntax)
> chore: add in rudimentary typings

- templates/python-beautifulsoup/requirements.txt
- templates/python-empty/requirements.txt
- templates/python-playwright/requirements.txt
- templates/python-scrapy/requirements.txt
- templates/python-selenium/requirements.txt
- templates/python-start/requirements.txt
- wrappers/python-scrapy/requirements_apify.txt
This should fix the failing tests. We might want to make the requirements looser and just install the latest version.
> chore: update version requirements for python sdk

- templates/js-bootstrap-cheerio-crawler/.actor/Dockerfile
- templates/js-crawlee-cheerio/.actor/Dockerfile
- templates/js-crawlee-playwright-chrome/.actor/Dockerfile
- templates/js-crawlee-puppeteer-chrome/.actor/Dockerfile
- templates/js-empty/.actor/Dockerfile
- templates/js-langchain/.actor/Dockerfile
- templates/js-start/.actor/Dockerfile
- templates/ts-bootstrap-cheerio-crawler/.actor/Dockerfile
- templates/ts-crawlee-cheerio/.actor/Dockerfile
- templates/ts-crawlee-playwright-chrome/.actor/Dockerfile
- templates/ts-crawlee-puppeteer-chrome/.actor/Dockerfile
- templates/ts-empty/.actor/Dockerfile
- templates/ts-playwright-test-runner/.actor/Dockerfile
- templates/ts-start/.actor/Dockerfile
Not sure if we have some good test suite to make sure the templates/SDK/Crawlee don't break down in Node 20. You know this random crap likes to happen :)
> chore: update Node.js 18 -> 20 in all templates

- templates/python-playwright/.actor/Dockerfile
based on [Slack bug report](https://apify.slack.com/archives/C0L33UM7Z/p1718270319985559):
```text
There is a problem with the [Playwright + Chrome template](https://console.apify.com/actors/templates/python-playwright). When you use the template, build the Actor and try to run it, it returns this to the log:
playwright._impl._api_types.Error: Executable doesn't exist at /root/.cache/ms-playwright/chromium-1084/chrome-linux/chrome
Looks like Playwright was just installed or updated.
Please run the following command to download new browsers:
playwright install
And then, when you add RUN playwright install to the Dockerfile, there is one more error, this time with playwright install-deps.
Only then, after you add RUN playwright install-deps to the Dockerfile, it finally works.
```
> fix: python playwright template

- templates/js-crawlee-puppeteer-chrome/.actor/input_schema.json
- templates/ts-crawlee-puppeteer-chrome/.actor/input_schema.json
Fix incorrect input_schema.json titles in crawlee-puppeteer-chrome templates
> fix: incorrect input_schema.json titles

- .github/workflows/lint_and_test.yaml
The broken template tests cost us $500 in the last month, because the tests were running for 6 hours before they timed out. This adds a 1-hour time limit to them, so that next time they time out earlier and it's not so costly.
I checked and the tests typically run for 30 minutes, so 1 hour timeout should be enough.
> fix: Add 60 minutes timeout to template tests

- README.md
- templates/js-langchain/.eslintrc
- templates/js-langchain/README.md
- templates/js-langchain/package.json
- templates/js-langchain/src/main.js
- templates/js-langchain/src/vector_index_cache.js
Update js-langchain template:
- Update dependencies.
- Move hnswlib and ApifyDatasetLoader to `langchain/community` and refactor code accordingly.
- Remove deprecated `RetrievalQaChain`.
- Replace `console.log()` with `Apify.log()`.
- Add eslint.
> fix: Update js-langchain template

- templates/manifest.json
- templates/python-beautifulsoup/README.md
- templates/python-crawlee-beautifulsoup/README.md
- templates/python-crawlee-playwright/README.md
- templates/python-empty/README.md
- templates/python-playwright/README.md
- templates/python-scrapy/README.md
- templates/python-selenium/README.md
- templates/python-standby/README.md
it should be (more) in accordance with the JS templates
> docs: update titles of python templates

- templates/js-bootstrap-cheerio-crawler/package.json
- templates/js-crawlee-cheerio/package.json
- templates/js-crawlee-playwright-chrome/package.json
- templates/js-crawlee-puppeteer-chrome/package.json
- templates/js-cypress/package.json
- templates/js-empty/package.json
- templates/js-langchain/package.json
- templates/js-standby/package.json
- templates/js-start/package.json
- templates/ts-bootstrap-cheerio-crawler/package.json
- templates/ts-crawlee-cheerio/package.json
- templates/ts-crawlee-playwright-chrome/package.json
- templates/ts-crawlee-puppeteer-chrome/package.json
- templates/ts-empty/package.json
- templates/ts-playwright-test-runner/package.json
- templates/ts-standby/package.json
- templates/ts-start-bun/package.json
- templates/ts-start/package.json
This is done manually like this once a while?
> chore: bump templates to latest crawlee & apify version

- templates/js-langchain/package.json
In the latest version of langchainjs we've modified the user agent (addded `Origin/langchainjs`) for the apify-client to attribute API activity to langchainjs
> feat: Update js-langchain template to pin langchainjs to the latest version

- templates/js-crawlee-playwright-chrome/src/main.js
- templates/js-crawlee-puppeteer-chrome/src/main.js
- templates/python-crawlee-playwright/src/main.py
- templates/python-playwright/src/main.py
- templates/ts-crawlee-playwright-chrome/src/main.ts
- templates/ts-crawlee-puppeteer-chrome/src/main.ts
- templates/ts-playwright-test-runner/.actor/Dockerfile
- templates/ts-playwright-test-runner/.dockerignore
- templates/ts-playwright-test-runner/.gitignore
- templates/ts-playwright-test-runner/package.json
- templates/ts-playwright-test-runner/src/main.ts
- templates/ts-playwright-test-runner/tests/first.spec.ts
Bumps the Playwright and Node versions in the template to `latest`s. Fixes the hanging `browserContext.newPage()` call by passing the `--disable-gpu` launch option to the browser.
More context at https://apify.slack.com/archives/CGZSN9DQC/p1733928283797729
> chore: bump `ts-playwright-test-runner` Playwright and Node version

- templates/js-crawlee-playwright-camoufox/.actor/Dockerfile
- templates/js-crawlee-playwright-camoufox/.actor/actor.json
- templates/js-crawlee-playwright-camoufox/.actor/input_schema.json
- templates/js-crawlee-playwright-camoufox/.dockerignore
- templates/js-crawlee-playwright-camoufox/.editorconfig
- templates/js-crawlee-playwright-camoufox/.eslintrc
- templates/js-crawlee-playwright-camoufox/.gitignore
- templates/js-crawlee-playwright-camoufox/README.md
- templates/js-crawlee-playwright-camoufox/package.json
- templates/js-crawlee-playwright-camoufox/src/main.js
- templates/js-crawlee-playwright-camoufox/src/routes.js
- templates/manifest.json
- templates/ts-crawlee-playwright-camoufox/.actor/Dockerfile
- templates/ts-crawlee-playwright-camoufox/.actor/actor.json
- templates/ts-crawlee-playwright-camoufox/.actor/input_schema.json
- templates/ts-crawlee-playwright-camoufox/.dockerignore
- templates/ts-crawlee-playwright-camoufox/.editorconfig
- templates/ts-crawlee-playwright-camoufox/.eslintrc
- templates/ts-crawlee-playwright-camoufox/.gitignore
- templates/ts-crawlee-playwright-camoufox/README.md
- templates/ts-crawlee-playwright-camoufox/package.json
- templates/ts-crawlee-playwright-camoufox/src/main.ts
- templates/ts-crawlee-playwright-camoufox/src/routes.ts
- templates/ts-crawlee-playwright-camoufox/tsconfig.json
Following the https://github.com/apify/apify-sdk-js/pull/364 and https://github.com/apify/crawlee/pull/2842 , this PR adds Camoufox-enabled templates to Apify Actor templates. The implementation is heavily based on the existing Playwright + Chrome templates.
The only issue (I'm aware of) currently is the immense size of those images (as they contain Chrome and we add Camoufox binaries). Installing Camoufox directly to a `node-debian` image results in missing system dependencies. While it might be possible to install those manually in the Dockerfile, it might make the Dockerfile too complex for a regular user.
> feat: add Camoufox-based Crawlee JS/TS templates

- templates/ts-crawlee-playwright-camoufox/package.json
The previous state was a result of a copy-paste error from other Playwright templates. This aligns the `ts-crawlee-playwright-camoufox` with the `js-crawlee-playwright-camoufox` template.
> fix: install `Camoufox` browsers in TS Camoufox template

- templates/js-crawlee-playwright-camoufox/.actor/Dockerfile
- templates/js-crawlee-playwright-camoufox/package.json
- templates/ts-crawlee-playwright-camoufox/.actor/Dockerfile
- templates/ts-crawlee-playwright-camoufox/package.json
Updates `camoufox-js` in templates to the latest version. This now respects the `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` flag. We need to disable this in the Dockerfiles, as the base images set this flag to `1`.
> fix: do not skip `camoufox` install in Docker build

- templates/python-beautifulsoup/.actor/Dockerfile
- templates/python-crawlee-beautifulsoup/.actor/Dockerfile
- templates/python-crawlee-playwright/.actor/Dockerfile
- templates/python-crewai/.actor/Dockerfile
- templates/python-empty/.actor/Dockerfile
- templates/python-langgraph/.actor/Dockerfile
- templates/python-llamaindex-agent/.actor/Dockerfile
- templates/python-playwright/.actor/Dockerfile
- templates/python-scrapy/.actor/Dockerfile
- templates/python-selenium/.actor/Dockerfile
- templates/python-standby/.actor/Dockerfile
- templates/python-start/.actor/Dockerfile
- wrappers/python-scrapy/.actor/Dockerfile.template
If we use:
```
RUN python3 -m compileall -q .
```
as a result, it will be executed on `site-packages` as well, resulting in:
since we have cookie-cutter templates inside.
> fix: Fix docker build of Python Crawlee templates

- templates/ts-playwright-test-runner/package.json
Because of [recent changes](https://github.com/apify/apify-cli/blame/d8ef00071c4138a441dec2d5336bba51b3143708/src/lib/hooks/useCwdProject.ts#L147) in Apify CLI, the stray `"main"` field in `ts-playwright-test-runner`'s package.json file caused the test to fail.
This would have caused problems for any users running the template-initialized test with `npx apify-cli run`.
> fix: remove stray "main" field in the `ts-playwright-test-runner` test

- templates/js-crawlee-playwright-camoufox/package.json
- templates/ts-crawlee-playwright-camoufox/package.json
Bumps Camoufox in the respective templates to the latest version available. This enables the template users to use the latest patches from `camoufox-js`.
> chore: bump Camoufox version

- templates/ts-crawlee-cheerio/src/main.ts
- templates/ts-crawlee-playwright-camoufox/src/main.ts
- templates/ts-crawlee-playwright-chrome/src/main.ts
- templates/ts-crawlee-puppeteer-chrome/src/main.ts
The `requestListSources` editor in the Actor input creates objects with URLs, not just string arrays. The types in the templates didn't match that.
> fix: Correct the type for `startUrls` input in TypeScript templates

- templates/ts-mcp-server/README.md
- templates/ts-mcp-server/package.json
- templates/ts-mcp-server/src/main.ts
The @modelcontextprotocol/server-sequential-thinking was confusing for human users, changed MCP server to @modelcontextprotocol/server-everything which is more human user friendly
> fix: change ts-mcp-template server to @modelcontextprotocol/server-everything

- eslint.config.mjs
- templates/js-crawlee-puppeteer-chrome/README.md
- templates/ts-crawlee-puppeteer-chrome/README.md
in my previous PR https://github.com/apify/actor-templates/pull/448 the puppeteer templates were failing on npm run format README.md check I fixed that formatting issue. Also noticed that when running eslint in the root it fails on venv and .venv dirs so I added them to ignore (also added node_modules just in case).
> fix: puppeteer templates that failed on README.md npm run format and ignore venv/.venv and node_modules in eslint config

- templates/python-mcp-server/.actor/actor.json
- templates/python-mcp-server/README.md
- templates/python-mcp-server/src/event_store.py
- templates/python-mcp-server/src/main.py
- templates/python-mcp-server/src/server.py
Add /mcp endpoint so the standby MCP server Actor support the "new" streamable HTTP transport. Fix None type error when closing SSE connection.
> feat(python-mcp-server): add streamable HTTP /mcp endpoint

- templates/ts-mcp-server/src/main.ts
- templates/ts-mcp-server/src/mcp.ts
- templates/ts-mcp-server/src/server.ts
When working on the new MCP server, I noticed that in the template we're not charging the legacy SSE endpoints 🤦. There was also an issue with the protocolVersion mismatch that broke the whole MCP server - we need to return the same version that the client sends in the request.
> fix(ts-mcp-server): bill the legacy SSE endpoints correctly and fix the initialize protocol version client mismatch

- templates/ts-mcp-server/src/server.ts
> fix: Remove double charing in ts-mcp template
